// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2018-07-25 12:54:47.539006953 +0200 CEST m=+0.037684465

package docs

import (
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "This is api sample doc.",
        "title": "API Swagger",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Giorgio Modoni",
            "url": "http://",
            "email": "modogio@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "1.0"
    },
    "host": "localhost:8080",
    "basePath": "/api",
    "paths": {
        "/": {
            "get": {
                "description": "this is the home of API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Show home route"
            }
        },
        "/v1/health": {
            "get": {
                "description": "like a ping with a simple response",
                "produces": [
                    "application/json"
                ],
                "summary": "health response"
            }
        },
        "/v1/ping": {
            "get": {
                "description": "this is the home of API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Ping response"
            }
        }
    }
}`

type s struct{}

func (s *s) ReadDoc() string {
	return doc
}
func init() {
	swag.Register(swag.Name, &s{})
}
